spring.application.name=recruito

#Database conncetion
spring.datasource.url=jdbc:oracle:thin:@10.10.10.194:1522:training
spring.datasource.username=angular1
spring.datasource.password=orcl123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging for debugging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE